[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jetstream"
version = "1.7.5"
description = "NGS analysis pipeline at TGen"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.7"
authors = [{ name = "Ryan Richholt", email = "ryan@tgen.org" }]
maintainers = [{ name = "Bryce Turner", email = "bturner@tgen.org" }]
keywords = ["ngs", "pipeline", "automation"]
classifiers = ["Development Status :: 3 - Alpha", "Topic :: Utilities"]
dependencies = [
  "networkx>=2.6,<3",
  "pyyaml",
  "ulid-py",
  "jinja2>=3.0.0",
  "filelock",
  "confuse",
  "packaging",
]

[project.optional-dependencies]
dev = ["pytest", "pytest-cov"]

[project.scripts]
jetstream = "jetstream.cli:main"

[project.urls]
Homepage = "https://github.com/tgen/jetstream"
Repository = "https://github.com/tgen/jetstream"
